package proxy

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
)

func ExportResults(results []*APIProxyResult, path string) error {
	if path == "" { path = "exports/api_proxies.json" }
	dir := path
	for i := len(path)-1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' { dir = path[:i]; break }
	}
	if dir != path { os.MkdirAll(dir, 0755) }
	sort.Slice(results, func(i, j int) bool { return results[i].Latency < results[j].Latency })
	type ExportData struct {
		Generated   string            `json:"generated"`
		AliveCount  int               `json:"alive_count"`
		TotalModels int               `json:"total_models"`
		Proxies     []*APIProxyResult `json:"proxies"`
	}
	totalModels := 0
	for _, r := range results { totalModels += r.ModelsCount }
	data := ExportData{Generated: time.Now().UTC().Format(time.RFC3339), AliveCount: len(results), TotalModels: totalModels, Proxies: results}
	file, _ := os.Create(path)
	defer file.Close()
	enc := json.NewEncoder(file)
	enc.SetIndent("", "  ")
	return enc.Encode(data)
}

func ExportHermesFormat(results []*APIProxyResult, path string) error {
	if path == "" { path = "exports/hermes_providers.yaml" }
	dir := path
	for i := len(path)-1; i >= 0; i-- {
		if path[i] == '/' || path[i] == '\\' { dir = path[:i]; break }
	}
	if dir != path { os.MkdirAll(dir, 0755) }
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by APOXY at %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("# Alive proxies: %d\n# Format: Hermes custom_providers\n\n", len(results)))
	sb.WriteString("custom_providers:\n")
	for i, r := range results {
		sb.WriteString(fmt.Sprintf("  - name: apoxy-found-%d\n", i))
		sb.WriteString(fmt.Sprintf("    base_url: %s\n", r.URL))
		sb.WriteString("    provider: openai\n    api_key: ''\n    discover_models: false\n    models:\n")
		limit := len(r.Models)
		if limit > 10 { limit = 10 }
		for _, m := range r.Models[:limit] {
			sb.WriteString(fmt.Sprintf("      %s:\n        ctx: 131072\n", m))
		}
		sb.WriteString("\n")
	}
	return os.WriteFile(path, []byte(sb.String()), 0644)
}
